### ISSUE TITLE
Won't connect after updating switchbot curtain firmware to 4.6

### ISSUE THREAD

**Issue by pranktap** [devWaves/SwitchBot-MQTT-BLE-ESP32#80]
I updated my curtain firmware to v 4.6 and now this will not find my curtains. It was working fine before the uprade. Is this just me?

**Comment by holdestmade** [comment]
Same here

**Comment by devWaves** [comment]
well crap....

For future reference, if it is working, I suggest not to upgrade the firmware. I will try to fix it though. I am not ready to upgrade my curtains yet if it has an issue, so I will need some help from you

it looks like the documentation for curtain has not been updated for firmware 4.6
github.com/OpenWonderLabs/SwitchBotAPI-BLE/blob/latest/devicetypes/curtain.md#0x45-curtain-setting-command
github.com/OpenWonderLabs/SwitchBotAPI-BLE/issues/4

a few questions/comments:

1. is it only control that is not working? if you control the curtain with your phone then reboot the esp32, are the values updated in mqtt/HA?
2. can you test sending a command using the nRF connect app? here is an example of how to send commands to the curtain https://github.com/devWaves/SwitchBot-MQTT-BLE-ESP32/issues/48#issuecomment-1004152003
3. also using nRF connect app, can you provide some screenshots of what the the "Service Data" and what the UUID looks like. Perform a scan with nRF connect and find the device MAC address. Take a bunch of screenshots with the associated position % the curtain should be at. So do like 0% position, then scan in nRF connect and take a screenshot. Then 100%, then scan again in nRF connect and take a screenshot. Then 50%, then scan again in nRF connect and take a screenshot.

**Comment by pranktap** [comment]
While troubleshooting the devices no longer show up in MQTT or home assistant anymore :( I’ll use the app tomorrow and get
You those values.

**Comment by lst3245** [comment]
For 1), both the control and sensors are not working in HA. Sensors like battery and linkquality have no update since upgrading but illuminance and position seem to have some random garbage value updates (illuminance sometimes has unavailable value but stays at level 1, when it definitely is not 1 in the daytime, position seems to be jumping randomly)
![lqi](https://user-images.githubusercontent.com/14272828/175807558-1bf4bd0b-99e6-4ad5-a0e4-1d3ba23944b9.png)
![lux](https://user-images.githubusercontent.com/14272828/175807565-279f96fa-ccf3-4076-a4fd-30863e700ab7.png)
![pos](https://user-images.githubusercontent.com/14272828/175807567-dd14b49c-f762-4332-8a27-216995008693.png)

For 2) and 3), I can control the curtain just fine using the 00, 32, 64 values for 0%, 50% and 100%. Here are the screenshots (although I am not sure if I have done it correctly):

00
<img src="https://user-images.githubusercontent.com/14272828/175807603-4ce7c276-e4eb-4a42-bf49-4bf1c5f91350.png" width="300">
<img src="https://user-images.githubusercontent.com/14272828/175807607-f070cf45-3e9a-48c1-a6f3-15d12505f475.png" width="300">
<img src="https://user-images.githubusercontent.com/14272828/175807609-14e06e52-7f66-40ed-ad79-717e8edffdeb.png" width="300">

64
<img src="https://user-images.githubusercontent.com/14272828/175807651-77546b99-2896-4de7-880d-2905b8afd7e7.png" width="300">
<img src="https://user-images.githubusercontent.com/14272828/175807656-3fec120a-5660-4d9e-8a31-51ace5b81e4d.png" width="300">
<img src="https://user-images.githubusercontent.com/14272828/175807660-6cd6866b-7f4f-4fc6-b4f1-0d3fb2d1cd4c.png" width="300">

32
<img src="https://user-images.githubusercontent.com/14272828/175807665-5195b427-91cb-44ab-b5d3-6a7c6386f5b0.png" width="300">
<img src="https://user-images.githubusercontent.com/14272828/175807668-74894448-606b-4785-a692-f345f38626bc.png" width="300">
<img src="https://user-images.githubusercontent.com/14272828/175807669-d6f74caa-8be0-4fdb-a7ab-92b4d786d90c.png" width="300">

**Comment by devWaves** [comment]
@lst3245 thanks that is some good info. I think I found the problem. They have updated the UUID. It used to be 0x0D00, now it is 0xFD3D. It seems the newer devices and firmwares are being updated to use that value. Not sure why, but this should fix it...

in the code edit this line:
```if ((advertisedDevice->isAdvertisingService(NimBLEUUID("cba20d00-224d-11e6-9fb8-0002a5d5c51b"))) || isContactDevice(deviceName) || isMotionDevice(deviceName) || isMeterDevice(deviceName))```

to this...
```if ((advertisedDevice->isAdvertisingService(NimBLEUUID("cba20d00-224d-11e6-9fb8-0002a5d5c51b"))) || isContactDevice(deviceName) || isMotionDevice(deviceName) || isMeterDevice(deviceName) || isCurtainDevice(deviceName))```


the difference is the isCurtainDevice(deviceName) part added

I have the feeling all newer firmware updates will start using this UUID so I might just update it for the bot as well in anticipation

**Comment by lst3245** [comment]
> @lst3245 thanks that is some good info. I think I found the problem. They have updated the UUID. It used to be 0x0D00, now it is 0xFD3D. It seems the newer devices and firmwares are being updated to use that value. Not sure why, but this should fix it...
> 
> in the code edit this line: `if ((advertisedDevice->isAdvertisingService(NimBLEUUID("cba20d00-224d-11e6-9fb8-0002a5d5c51b"))) || isContactDevice(deviceName) || isMotionDevice(deviceName) || isMeterDevice(deviceName))`
> 
> to this... `if ((advertisedDevice->isAdvertisingService(NimBLEUUID("cba20d00-224d-11e6-9fb8-0002a5d5c51b"))) || isContactDevice(deviceName) || isMotionDevice(deviceName) || isMeterDevice(deviceName) || isCurtainDevice(deviceName))`
> 
> the difference is the isCurtainDevice(deviceName) part added
> 
> I have the feeling all newer firmware updates will start using this UUID so I might just update it for the bot as well in anticipation

Thanks so much. Just compiled the firmware again and it's working well in HA now. Much appreciated your effort :)

**Comment by holdestmade** [comment]
> @lst3245 thanks that is some good info. I think I found the problem. They have updated the UUID. It used to be 0x0D00, now it is 0xFD3D. It seems the newer devices and firmwares are being updated to use that value. Not sure why, but this should fix it...
> 
> in the code edit this line: `if ((advertisedDevice->isAdvertisingService(NimBLEUUID("cba20d00-224d-11e6-9fb8-0002a5d5c51b"))) || isContactDevice(deviceName) || isMotionDevice(deviceName) || isMeterDevice(deviceName))`
> 
> to this... `if ((advertisedDevice->isAdvertisingService(NimBLEUUID("cba20d00-224d-11e6-9fb8-0002a5d5c51b"))) || isContactDevice(deviceName) || isMotionDevice(deviceName) || isMeterDevice(deviceName) || isCurtainDevice(deviceName))`
> 
> the difference is the isCurtainDevice(deviceName) part added
> 
> I have the feeling all newer firmware updates will start using this UUID so I might just update it for the bot as well in anticipation

This worked for me too, many thanks

**Comment by devWaves** [comment]
fix applied in v6.11

I applied the same style fix for the bot if they ever change the UUID

**Comment by mike1627** [comment]
> in the code edit this line: `if ((advertisedDevice->isAdvertisingService(NimBLEUUID("cba20d00-224d-11e6-9fb8-0002a5d5c51b"))) || isContactDevice(deviceName) || isMotionDevice(deviceName) || isMeterDevice(deviceName))`

I just stumbled across this thread, I'm having the same issues here.  Which file in HA are you referring to that has this code?

**Comment by devWaves** [comment]
@mike1627 hey there are no files to change in HA for this as it uses an ESP32. Firmware 4.6 starts using the new UUID = 0xFD3D = "0000fd3d-0000-1000-8000-00805f9b34fb", where before firmware 4.6 it used UUID = 0x0D00 = "cba20d00-224d-11e6-9fb8-0002a5d5c51b"

I am only given the option to upgrade to v4.4 at the moment, so it looks like v4.6 hasn't reached the Switchbot server I connect to. But others have confirmed that was the issue

@RenierM26 adding you so you are aware
